name: Deploy master
on:
  push:
    branches: [ master ]    
jobs:
  build:  
    runs-on: ubuntu-latest
    
    steps:      
      - name: Checkout source code      
        uses: actions/checkout@v2
      
      - name: Executa o NPM
        run: | 
          npm install
          npm run production
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
    
