name: Deploy master
on:
  push:
    branches:
    - master    
jobs:
  build:
    environment: production   
    runs-on: ubuntu-latest
    
    steps:
      
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'
      
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.APPLICATION_NAME }}
        environment_name: ${{ env.ENVIRONMENT_NAME }}
        version_label: 12345
        region: ${{ env.AWS_DEFAULT_REGION }}
        deployment_package: deploy.zip
